/* Auto-generated by tools/gen_kat_vectors.py — do not edit.
 * ML-DSA-65 ACVP vectors: 115 total test cases
 */
#ifndef KAT_VECTORS_H
#define KAT_VECTORS_H
#include <stdint.h>
#include <stddef.h>

/* sigGen: internal sign (det / non-det) */
typedef struct {
    int           tcId;
    const uint8_t *sk;
    const uint8_t *msg;
    size_t         mlen;
    uint8_t        rnd[32];   /* zeros for deterministic */
    const uint8_t *exp_sig;
} siggen_int_tc_t;

/* sigGen: external / pure sign (det / non-det) */
typedef struct {
    int           tcId;
    const uint8_t *sk;
    const uint8_t *msg;
    size_t         mlen;
    const uint8_t *ctx;
    size_t         ctxlen;
    uint8_t        rnd[32];   /* zeros for deterministic */
    const uint8_t *exp_sig;
} siggen_ext_tc_t;

/* sigVer: internal */
typedef struct {
    int           tcId;
    int           exp_pass;
    const uint8_t *pk;
    const uint8_t *msg;
    size_t         mlen;
    const uint8_t *sig;
} sigver_int_tc_t;

/* sigVer: external / pure */
typedef struct {
    int           tcId;
    int           exp_pass;
    const uint8_t *pk;
    const uint8_t *msg;
    size_t         mlen;
    const uint8_t *ctx;
    size_t         ctxlen;
    const uint8_t *sig;
} sigver_ext_tc_t;

/* keyGen */
typedef struct {
    int     tcId;
    uint8_t seed[32];
    const uint8_t *exp_pk;
    const uint8_t *exp_sk;
} keygen_tc_t;

/* Test-case counts */
#define KAT_SIGGEN_INT_DET_N   15    /* tgId=10  internal / det   */
#define KAT_SIGGEN_INT_NDET_N  15   /* tgId=22  internal / ndet  */
#define KAT_SIGGEN_EXT_DET_N   15    /* tgId=3   external / det   */
#define KAT_SIGGEN_EXT_NDET_N  15   /* tgId=15  external / ndet  */
#define KAT_SIGVER_INT_N        15   /* tgId=10   sigVer / int    */
#define KAT_SIGVER_EXT_N        15   /* tgId=3   sigVer / ext    */
#define KAT_KEYGEN_N             25   /* tgId=2          keyGen         */
#define KAT_TOTAL_N              115

/* Arrays defined in kat_data.c */
extern const siggen_int_tc_t kat_siggen_sg10[KAT_SIGGEN_INT_DET_N];
extern const siggen_int_tc_t kat_siggen_sg22[KAT_SIGGEN_INT_NDET_N];
extern const siggen_ext_tc_t kat_siggen_sg03[KAT_SIGGEN_EXT_DET_N];
extern const siggen_ext_tc_t kat_siggen_sg15[KAT_SIGGEN_EXT_NDET_N];
extern const sigver_int_tc_t kat_sigver_sv10[KAT_SIGVER_INT_N];
extern const sigver_ext_tc_t kat_sigver_sv03[KAT_SIGVER_EXT_N];
extern const keygen_tc_t     kat_keygen_kg02[KAT_KEYGEN_N];

#endif /* KAT_VECTORS_H */
