/* Auto-generated by tools/gen_kat_vectors.py — do not edit.
 * ML-DSA-44 ACVP vectors: 115 total test cases
 */
#ifndef KAT_VECTORS44_H
#define KAT_VECTORS44_H
#include <stdint.h>
#include <stddef.h>

/* sigGen: internal sign (det / non-det) */
typedef struct {
    int           tcId;
    const uint8_t *sk;
    const uint8_t *msg;
    size_t         mlen;
    uint8_t        rnd[32];   /* zeros for deterministic */
    const uint8_t *exp_sig;
} siggen_int_tc44_t;

/* sigGen: external / pure sign (det / non-det) */
typedef struct {
    int           tcId;
    const uint8_t *sk;
    const uint8_t *msg;
    size_t         mlen;
    const uint8_t *ctx;
    size_t         ctxlen;
    uint8_t        rnd[32];   /* zeros for deterministic */
    const uint8_t *exp_sig;
} siggen_ext_tc44_t;

/* sigVer: internal */
typedef struct {
    int           tcId;
    int           exp_pass;
    const uint8_t *pk;
    const uint8_t *msg;
    size_t         mlen;
    const uint8_t *sig;
} sigver_int_tc44_t;

/* sigVer: external / pure */
typedef struct {
    int           tcId;
    int           exp_pass;
    const uint8_t *pk;
    const uint8_t *msg;
    size_t         mlen;
    const uint8_t *ctx;
    size_t         ctxlen;
    const uint8_t *sig;
} sigver_ext_tc44_t;

/* keyGen */
typedef struct {
    int     tcId;
    uint8_t seed[32];
    const uint8_t *exp_pk;
    const uint8_t *exp_sk;
} keygen_tc44_t;

/* Test-case counts */
#define KAT44_SIGGEN_INT_DET_N   15    /* tgId=8  internal / det   */
#define KAT44_SIGGEN_INT_NDET_N  15   /* tgId=20  internal / ndet  */
#define KAT44_SIGGEN_EXT_DET_N   15    /* tgId=1   external / det   */
#define KAT44_SIGGEN_EXT_NDET_N  15   /* tgId=13  external / ndet  */
#define KAT44_SIGVER_INT_N        15   /* tgId=8   sigVer / int    */
#define KAT44_SIGVER_EXT_N        15   /* tgId=1   sigVer / ext    */
#define KAT44_KEYGEN_N             25   /* tgId=1          keyGen         */
#define KAT44_TOTAL_N              115

/* Arrays defined in kat_data44.c */
extern const siggen_int_tc44_t kat_siggen_sg08[KAT44_SIGGEN_INT_DET_N];
extern const siggen_int_tc44_t kat_siggen_sg20[KAT44_SIGGEN_INT_NDET_N];
extern const siggen_ext_tc44_t kat_siggen_sg01[KAT44_SIGGEN_EXT_DET_N];
extern const siggen_ext_tc44_t kat_siggen_sg13[KAT44_SIGGEN_EXT_NDET_N];
extern const sigver_int_tc44_t kat_sigver_sv08[KAT44_SIGVER_INT_N];
extern const sigver_ext_tc44_t kat_sigver_sv01[KAT44_SIGVER_EXT_N];
extern const keygen_tc44_t     kat_keygen_kg01[KAT44_KEYGEN_N];

#endif /* KAT_VECTORS44_H */
