/*
 * gen_mlkem768_kat.c —
 *   Generator for kat_mlkem768.h.  Runs the PQClean ML-KEM-768
 *   reference natively with deterministic seeds and prints the
 *   expected outputs as a C header.
 *
 * Build (macOS/Linux host):
 *   cc -O2 -I../ref_kem -I../vendor/mupq-common -I../vendor/pqm4-common \
 *      gen_mlkem768_kat.c \
 *      ../ref_kem/*.c \
 *      ../vendor/mupq-common/fips202.c ../vendor/mupq-common/keccakf1600.c \
 *      -o gen_mlkem768_kat
 *   ./gen_mlkem768_kat > ../test/kat_mlkem768.h
 */

#include <stdio.h>
#include <stdint.h>
#include <string.h>

#include "api.h"   /* ref_kem/api.h */
#include "kem.h"   /* ref_kem/kem.h — _derand variants */

/* Stub: the generator only uses _derand paths so this never runs. */
int randombytes(uint8_t *buf, size_t n) { (void)buf; (void)n; return -1; }

/* Deterministic seeds (chosen so vectors differ trivially). */
#define NVEC 3
static const uint8_t KP_SEEDS[NVEC][64] = {
    {0x00,0x01,0x02,0x03,0x04,0x05,0x06,0x07,0x08,0x09,0x0a,0x0b,0x0c,0x0d,0x0e,0x0f,
     0x10,0x11,0x12,0x13,0x14,0x15,0x16,0x17,0x18,0x19,0x1a,0x1b,0x1c,0x1d,0x1e,0x1f,
     0xa0,0xa1,0xa2,0xa3,0xa4,0xa5,0xa6,0xa7,0xa8,0xa9,0xaa,0xab,0xac,0xad,0xae,0xaf,
     0xb0,0xb1,0xb2,0xb3,0xb4,0xb5,0xb6,0xb7,0xb8,0xb9,0xba,0xbb,0xbc,0xbd,0xbe,0xbf},
    {0xde,0xad,0xbe,0xef, 0xde,0xad,0xbe,0xef, 0xde,0xad,0xbe,0xef, 0xde,0xad,0xbe,0xef,
     0xca,0xfe,0xba,0xbe, 0xca,0xfe,0xba,0xbe, 0xca,0xfe,0xba,0xbe, 0xca,0xfe,0xba,0xbe,
     0xfe,0xed,0xfa,0xce, 0xfe,0xed,0xfa,0xce, 0xfe,0xed,0xfa,0xce, 0xfe,0xed,0xfa,0xce,
     0x01,0x23,0x45,0x67, 0x89,0xab,0xcd,0xef, 0xfe,0xdc,0xba,0x98, 0x76,0x54,0x32,0x10},
    {[0 ... 63] = 0x5A}
};
static const uint8_t ENC_COINS[NVEC][32] = {
    {0xe0,0xe1,0xe2,0xe3,0xe4,0xe5,0xe6,0xe7,0xe8,0xe9,0xea,0xeb,0xec,0xed,0xee,0xef,
     0xf0,0xf1,0xf2,0xf3,0xf4,0xf5,0xf6,0xf7,0xf8,0xf9,0xfa,0xfb,0xfc,0xfd,0xfe,0xff},
    {0x77,0x77,0x77,0x77, 0x77,0x77,0x77,0x77, 0x77,0x77,0x77,0x77, 0x77,0x77,0x77,0x77,
     0x77,0x77,0x77,0x77, 0x77,0x77,0x77,0x77, 0x77,0x77,0x77,0x77, 0x77,0x77,0x77,0x77},
    {[0 ... 31] = 0xA5}
};

static void print_bytes(const char *name, const uint8_t *b, size_t n) {
    printf("static const uint8_t %s[%zu] = {\n    ", name, n);
    for (size_t i = 0; i < n; i++) {
        printf("0x%02x", b[i]);
        if (i + 1 < n) printf(",");
        if ((i & 15) == 15 && i + 1 < n) printf("\n    ");
        else if (i + 1 < n)              printf(" ");
    }
    printf("\n};\n");
}

int main(void) {
    uint8_t pk[PQCLEAN_MLKEM768_CLEAN_CRYPTO_PUBLICKEYBYTES];
    uint8_t sk[PQCLEAN_MLKEM768_CLEAN_CRYPTO_SECRETKEYBYTES];
    uint8_t ct[PQCLEAN_MLKEM768_CLEAN_CRYPTO_CIPHERTEXTBYTES];
    uint8_t ss_enc[PQCLEAN_MLKEM768_CLEAN_CRYPTO_BYTES];
    uint8_t ss_dec[PQCLEAN_MLKEM768_CLEAN_CRYPTO_BYTES];

    printf("/* Auto-generated by tools/gen_mlkem768_kat.c — DO NOT EDIT. */\n");
    printf("#ifndef KAT_MLKEM768_H\n");
    printf("#define KAT_MLKEM768_H\n\n");
    printf("#include <stdint.h>\n\n");
    printf("#define KAT_MLKEM768_NVEC %d\n\n", NVEC);

    /* Dump seeds */
    for (int i = 0; i < NVEC; i++) {
        char nm[32];
        snprintf(nm, sizeof nm, "kat768_kp_seed_%d", i);
        print_bytes(nm, KP_SEEDS[i], 64);
        snprintf(nm, sizeof nm, "kat768_enc_coins_%d", i);
        print_bytes(nm, ENC_COINS[i], 32);
    }
    printf("\n");

    /* Expected outputs */
    for (int i = 0; i < NVEC; i++) {
        PQCLEAN_MLKEM768_CLEAN_crypto_kem_keypair_derand(pk, sk, KP_SEEDS[i]);
        PQCLEAN_MLKEM768_CLEAN_crypto_kem_enc_derand(ct, ss_enc, pk, ENC_COINS[i]);
        PQCLEAN_MLKEM768_CLEAN_crypto_kem_dec(ss_dec, ct, sk);
        if (memcmp(ss_enc, ss_dec, sizeof ss_enc) != 0) {
            fprintf(stderr, "INTERNAL ERROR: ss mismatch on vec %d\n", i);
            return 1;
        }
        char nm[32];
        snprintf(nm, sizeof nm, "kat768_exp_pk_%d", i);     print_bytes(nm, pk, sizeof pk);
        snprintf(nm, sizeof nm, "kat768_exp_sk_%d", i);     print_bytes(nm, sk, sizeof sk);
        snprintf(nm, sizeof nm, "kat768_exp_ct_%d", i);     print_bytes(nm, ct, sizeof ct);
        snprintf(nm, sizeof nm, "kat768_exp_ss_%d", i);     print_bytes(nm, ss_enc, sizeof ss_enc);
        printf("\n");
    }

    /* Vector table */
    printf("typedef struct {\n");
    printf("    const uint8_t *kp_seed;       /* 64 bytes */\n");
    printf("    const uint8_t *enc_coins;     /* 32 bytes */\n");
    printf("    const uint8_t *exp_pk;        /* 1184 bytes */\n");
    printf("    const uint8_t *exp_sk;        /* 2400 bytes */\n");
    printf("    const uint8_t *exp_ct;        /* 1088 bytes */\n");
    printf("    const uint8_t *exp_ss;        /* 32 bytes   */\n");
    printf("} kat_mlkem768_t;\n\n");

    printf("static const kat_mlkem768_t kat_mlkem768[KAT_MLKEM768_NVEC] = {\n");
    for (int i = 0; i < NVEC; i++) {
        printf("    { kat768_kp_seed_%d, kat768_enc_coins_%d,\n", i, i);
        printf("      kat768_exp_pk_%d,  kat768_exp_sk_%d,\n", i, i);
        printf("      kat768_exp_ct_%d,  kat768_exp_ss_%d },\n", i, i);
    }
    printf("};\n\n");

    printf("#endif /* KAT_MLKEM768_H */\n");
    return 0;
}
