#!/usr/bin/env python3
"""
gen_kat_vectors.py — Generate C test-vector files from NIST ACVP JSON.

Reads:
  /tmp/sigGen.json, /tmp/sigVer.json, /tmp/keyGen.json
  (fetched from github.com/usnistgov/ACVP-Server)

Writes (ML-DSA-65):
  test/kat_vectors.h   — struct typedefs + extern declarations
  test/kat_data.c      — binary data + struct arrays

Writes (ML-DSA-44):
  test/kat_vectors44.h
  test/kat_data44.c

ML-DSA-65 groups:
  sigGen  tgId 10  internal / none    / deterministic
  sigGen  tgId 22  internal / none    / non-deterministic
  sigGen  tgId  3  external / pure    / deterministic
  sigGen  tgId 15  external / pure    / non-deterministic
  sigVer  tgId 10  internal / none
  sigVer  tgId  3  external / pure
  keyGen  tgId  2

ML-DSA-44 groups (same layout, different tgIds):
  sigGen  tgId  8  internal / none    / deterministic
  sigGen  tgId 20  internal / none    / non-deterministic
  sigGen  tgId  1  external / pure    / deterministic
  sigGen  tgId 13  external / pure    / non-deterministic
  sigVer  tgId  8  internal / none
  sigVer  tgId  1  external / pure
  keyGen  tgId  1
"""

import json
import os
import sys
import textwrap

OUT_DIR = os.path.join(os.path.dirname(__file__), '..', 'test')

SIGGEN_JSON = '/tmp/sigGen.json'
SIGVER_JSON = '/tmp/sigVer.json'
KEYGEN_JSON = '/tmp/keyGen.json'


def hex_to_c_array(name, hexstr):
    if not hexstr:
        return f'static const uint8_t {name}[1] = {{0}};'
    data = bytes.fromhex(hexstr)
    n    = len(data)
    lines = [f'static const uint8_t {name}[{n}] = {{']
    for i in range(0, n, 16):
        chunk = data[i:i+16]
        lines.append('    ' + ', '.join(f'0x{b:02x}' for b in chunk) + ',')
    lines.append('};')
    return '\n'.join(lines)


def write_file_header(f, note):
    f.write(f'/* Auto-generated by tools/gen_kat_vectors.py — do not edit.\n')
    f.write(f' * {note}\n')
    f.write(f' */\n')


# ------------------------------------------------------------------ #
# Load JSON                                                            #
# ------------------------------------------------------------------ #

for path in (SIGGEN_JSON, SIGVER_JSON, KEYGEN_JSON):
    if not os.path.exists(path):
        sys.exit(f'ERROR: {path} not found. Fetch from NIST ACVP-Server first.')

with open(SIGGEN_JSON) as f: sg_data = json.load(f)
with open(SIGVER_JSON) as f: sv_data = json.load(f)
with open(KEYGEN_JSON) as f: kg_data = json.load(f)


def get_tg(dataset, tg_id):
    for tg in dataset['testGroups']:
        if tg['tgId'] == tg_id:
            return tg
    sys.exit(f'ERROR: tgId={tg_id} not found')


# ------------------------------------------------------------------ #
# Generator for one parameter set                                      #
# ------------------------------------------------------------------ #

def generate(
    param_set,          # 'ML-DSA-65' or 'ML-DSA-44'
    sg_int_det_id,      # sigGen internal/det   tgId
    sg_int_ndet_id,     # sigGen internal/ndet  tgId
    sg_ext_det_id,      # sigGen external/det   tgId
    sg_ext_ndet_id,     # sigGen external/ndet  tgId
    sv_int_id,          # sigVer internal       tgId
    sv_ext_id,          # sigVer external       tgId
    kg_id,              # keyGen                tgId
    dat_path,           # output kat_data*.c path
    hdr_path,           # output kat_vectors*.h path
    label_suffix,       # '' for 65, '44' for 44
):
    sg_int_det  = get_tg(sg_data, sg_int_det_id)
    sg_int_ndet = get_tg(sg_data, sg_int_ndet_id)
    sg_ext_det  = get_tg(sg_data, sg_ext_det_id)
    sg_ext_ndet = get_tg(sg_data, sg_ext_ndet_id)
    sv_int      = get_tg(sv_data, sv_int_id)
    sv_ext      = get_tg(sv_data, sv_ext_id)
    kg          = get_tg(kg_data, kg_id)

    sfx = label_suffix   # e.g. '' or '44'

    # labels matching the tgId scheme used in C array names
    sg_int_det_lbl  = f'sg{sg_int_det_id:02d}'
    sg_int_ndet_lbl = f'sg{sg_int_ndet_id:02d}'
    sg_ext_det_lbl  = f'sg{sg_ext_det_id:02d}'
    sg_ext_ndet_lbl = f'sg{sg_ext_ndet_id:02d}'
    sv_int_lbl      = f'sv{sv_int_id:02d}'
    sv_ext_lbl      = f'sv{sv_ext_id:02d}'
    kg_lbl          = f'kg{kg_id:02d}'

    # ---- kat_data*.c ----
    with open(dat_path, 'w') as out:
        write_file_header(out, f'NIST ACVP {param_set} test vectors')
        out.write('#include <stdint.h>\n')
        out.write('#include <stddef.h>\n')
        out.write(f'#include "kat_vectors{sfx}.h"\n\n')

        # sigGen internal (det + ndet)
        for label, tg, det in [
            (sg_int_det_lbl,  sg_int_det,  True),
            (sg_int_ndet_lbl, sg_int_ndet, False),
        ]:
            for tc in tg['tests']:
                tid = tc['tcId']
                out.write(hex_to_c_array(f'{label}_tc{tid}_sk',  tc['sk'])      + '\n')
                out.write(hex_to_c_array(f'{label}_tc{tid}_msg', tc['message']) + '\n')
                out.write(hex_to_c_array(f'{label}_tc{tid}_sig', tc['signature']) + '\n')
                out.write('\n')

            out.write(f'const siggen_int_tc{sfx}_t kat_siggen_{label}[{len(tg["tests"])}] = {{\n')
            for tc in tg['tests']:
                tid  = tc['tcId']
                mlen = len(tc['message']) // 2
                if det:
                    rnd_init = '{0}'
                else:
                    rnd_bytes = bytes.fromhex(tc['rnd'])
                    rnd_init  = '{' + ', '.join(f'0x{b:02x}' for b in rnd_bytes) + '}'
                out.write(
                    f'    {{ {tid}, {label}_tc{tid}_sk, {label}_tc{tid}_msg, {mlen},\n'
                    f'      {rnd_init},\n'
                    f'      {label}_tc{tid}_sig }},\n'
                )
            out.write('};\n\n')

        # sigGen external (det + ndet)
        for label, tg, det in [
            (sg_ext_det_lbl,  sg_ext_det,  True),
            (sg_ext_ndet_lbl, sg_ext_ndet, False),
        ]:
            for tc in tg['tests']:
                tid = tc['tcId']
                out.write(hex_to_c_array(f'{label}_tc{tid}_sk',  tc['sk'])        + '\n')
                out.write(hex_to_c_array(f'{label}_tc{tid}_msg', tc['message'])    + '\n')
                out.write(hex_to_c_array(f'{label}_tc{tid}_ctx', tc['context'])    + '\n')
                out.write(hex_to_c_array(f'{label}_tc{tid}_sig', tc['signature'])  + '\n')
                out.write('\n')

            out.write(f'const siggen_ext_tc{sfx}_t kat_siggen_{label}[{len(tg["tests"])}] = {{\n')
            for tc in tg['tests']:
                tid    = tc['tcId']
                mlen   = len(tc['message']) // 2
                ctxlen = len(tc['context']) // 2
                if det:
                    rnd_init = '{0}'
                else:
                    rnd_bytes = bytes.fromhex(tc['rnd'])
                    rnd_init  = '{' + ', '.join(f'0x{b:02x}' for b in rnd_bytes) + '}'
                out.write(
                    f'    {{ {tid}, {label}_tc{tid}_sk, {label}_tc{tid}_msg, {mlen},\n'
                    f'      {label}_tc{tid}_ctx, {ctxlen},\n'
                    f'      {rnd_init},\n'
                    f'      {label}_tc{tid}_sig }},\n'
                )
            out.write('};\n\n')

        # sigVer internal
        for tc in sv_int['tests']:
            tid = tc['tcId']
            out.write(hex_to_c_array(f'{sv_int_lbl}_tc{tid}_pk',  tc['pk'])        + '\n')
            out.write(hex_to_c_array(f'{sv_int_lbl}_tc{tid}_msg', tc['message'])    + '\n')
            out.write(hex_to_c_array(f'{sv_int_lbl}_tc{tid}_sig', tc['signature'])  + '\n')
            out.write('\n')

        out.write(f'const sigver_int_tc{sfx}_t kat_sigver_{sv_int_lbl}[{len(sv_int["tests"])}] = {{\n')
        for tc in sv_int['tests']:
            tid    = tc['tcId']
            mlen   = len(tc['message']) // 2
            passed = 1 if tc['testPassed'] else 0
            out.write(
                f'    {{ {tid}, {passed}, {sv_int_lbl}_tc{tid}_pk,\n'
                f'      {sv_int_lbl}_tc{tid}_msg, {mlen}, {sv_int_lbl}_tc{tid}_sig }},\n'
            )
        out.write('};\n\n')

        # sigVer external
        for tc in sv_ext['tests']:
            tid = tc['tcId']
            out.write(hex_to_c_array(f'{sv_ext_lbl}_tc{tid}_pk',  tc['pk'])        + '\n')
            out.write(hex_to_c_array(f'{sv_ext_lbl}_tc{tid}_msg', tc['message'])    + '\n')
            out.write(hex_to_c_array(f'{sv_ext_lbl}_tc{tid}_ctx', tc['context'])    + '\n')
            out.write(hex_to_c_array(f'{sv_ext_lbl}_tc{tid}_sig', tc['signature'])  + '\n')
            out.write('\n')

        out.write(f'const sigver_ext_tc{sfx}_t kat_sigver_{sv_ext_lbl}[{len(sv_ext["tests"])}] = {{\n')
        for tc in sv_ext['tests']:
            tid    = tc['tcId']
            mlen   = len(tc['message']) // 2
            ctxlen = len(tc['context']) // 2
            passed = 1 if tc['testPassed'] else 0
            out.write(
                f'    {{ {tid}, {passed}, {sv_ext_lbl}_tc{tid}_pk,\n'
                f'      {sv_ext_lbl}_tc{tid}_msg, {mlen}, {sv_ext_lbl}_tc{tid}_ctx, {ctxlen},\n'
                f'      {sv_ext_lbl}_tc{tid}_sig }},\n'
            )
        out.write('};\n\n')

        # keyGen
        for tc in kg['tests']:
            tid = tc['tcId']
            out.write(hex_to_c_array(f'{kg_lbl}_tc{tid}_pk', tc['pk']) + '\n')
            out.write(hex_to_c_array(f'{kg_lbl}_tc{tid}_sk', tc['sk']) + '\n')
            out.write('\n')

        out.write(f'const keygen_tc{sfx}_t kat_keygen_{kg_lbl}[{len(kg["tests"])}] = {{\n')
        for tc in kg['tests']:
            tid       = tc['tcId']
            seed_bytes = bytes.fromhex(tc['seed'])
            seed_init  = '{' + ', '.join(f'0x{b:02x}' for b in seed_bytes) + '}'
            out.write(
                f'    {{ {tid}, {seed_init},\n'
                f'      {kg_lbl}_tc{tid}_pk, {kg_lbl}_tc{tid}_sk }},\n'
            )
        out.write('};\n\n')

    # ---- kat_vectors*.h ----
    n_sg_int_det  = len(sg_int_det['tests'])
    n_sg_int_ndet = len(sg_int_ndet['tests'])
    n_sg_ext_det  = len(sg_ext_det['tests'])
    n_sg_ext_ndet = len(sg_ext_ndet['tests'])
    n_sv_int      = len(sv_int['tests'])
    n_sv_ext      = len(sv_ext['tests'])
    n_kg          = len(kg['tests'])
    total = n_sg_int_det + n_sg_int_ndet + n_sg_ext_det + n_sg_ext_ndet + n_sv_int + n_sv_ext + n_kg

    guard = f'KAT_VECTORS{sfx.upper()}_H'

    with open(hdr_path, 'w') as out:
        write_file_header(out, f'{param_set} ACVP vectors: {total} total test cases')
        out.write(f'#ifndef {guard}\n#define {guard}\n')
        out.write('#include <stdint.h>\n#include <stddef.h>\n\n')

        out.write(textwrap.dedent(f"""\
            /* sigGen: internal sign (det / non-det) */
            typedef struct {{
                int           tcId;
                const uint8_t *sk;
                const uint8_t *msg;
                size_t         mlen;
                uint8_t        rnd[32];   /* zeros for deterministic */
                const uint8_t *exp_sig;
            }} siggen_int_tc{sfx}_t;

            /* sigGen: external / pure sign (det / non-det) */
            typedef struct {{
                int           tcId;
                const uint8_t *sk;
                const uint8_t *msg;
                size_t         mlen;
                const uint8_t *ctx;
                size_t         ctxlen;
                uint8_t        rnd[32];   /* zeros for deterministic */
                const uint8_t *exp_sig;
            }} siggen_ext_tc{sfx}_t;

            /* sigVer: internal */
            typedef struct {{
                int           tcId;
                int           exp_pass;
                const uint8_t *pk;
                const uint8_t *msg;
                size_t         mlen;
                const uint8_t *sig;
            }} sigver_int_tc{sfx}_t;

            /* sigVer: external / pure */
            typedef struct {{
                int           tcId;
                int           exp_pass;
                const uint8_t *pk;
                const uint8_t *msg;
                size_t         mlen;
                const uint8_t *ctx;
                size_t         ctxlen;
                const uint8_t *sig;
            }} sigver_ext_tc{sfx}_t;

            /* keyGen */
            typedef struct {{
                int     tcId;
                uint8_t seed[32];
                const uint8_t *exp_pk;
                const uint8_t *exp_sk;
            }} keygen_tc{sfx}_t;

            /* Test-case counts */
            #define KAT{sfx.upper()}_SIGGEN_INT_DET_N   {n_sg_int_det}    /* tgId={sg_int_det_id}  internal / det   */
            #define KAT{sfx.upper()}_SIGGEN_INT_NDET_N  {n_sg_int_ndet}   /* tgId={sg_int_ndet_id}  internal / ndet  */
            #define KAT{sfx.upper()}_SIGGEN_EXT_DET_N   {n_sg_ext_det}    /* tgId={sg_ext_det_id}   external / det   */
            #define KAT{sfx.upper()}_SIGGEN_EXT_NDET_N  {n_sg_ext_ndet}   /* tgId={sg_ext_ndet_id}  external / ndet  */
            #define KAT{sfx.upper()}_SIGVER_INT_N        {n_sv_int}   /* tgId={sv_int_id}   sigVer / int    */
            #define KAT{sfx.upper()}_SIGVER_EXT_N        {n_sv_ext}   /* tgId={sv_ext_id}   sigVer / ext    */
            #define KAT{sfx.upper()}_KEYGEN_N             {n_kg}   /* tgId={kg_id}          keyGen         */
            #define KAT{sfx.upper()}_TOTAL_N              {total}

            /* Arrays defined in kat_data{sfx}.c */
            extern const siggen_int_tc{sfx}_t kat_siggen_{sg_int_det_lbl}[KAT{sfx.upper()}_SIGGEN_INT_DET_N];
            extern const siggen_int_tc{sfx}_t kat_siggen_{sg_int_ndet_lbl}[KAT{sfx.upper()}_SIGGEN_INT_NDET_N];
            extern const siggen_ext_tc{sfx}_t kat_siggen_{sg_ext_det_lbl}[KAT{sfx.upper()}_SIGGEN_EXT_DET_N];
            extern const siggen_ext_tc{sfx}_t kat_siggen_{sg_ext_ndet_lbl}[KAT{sfx.upper()}_SIGGEN_EXT_NDET_N];
            extern const sigver_int_tc{sfx}_t kat_sigver_{sv_int_lbl}[KAT{sfx.upper()}_SIGVER_INT_N];
            extern const sigver_ext_tc{sfx}_t kat_sigver_{sv_ext_lbl}[KAT{sfx.upper()}_SIGVER_EXT_N];
            extern const keygen_tc{sfx}_t     kat_keygen_{kg_lbl}[KAT{sfx.upper()}_KEYGEN_N];

            #endif /* {guard} */
        """))

    return total, n_sg_int_det, n_sg_int_ndet, n_sg_ext_det, n_sg_ext_ndet, n_sv_int, n_sv_ext, n_kg


# ------------------------------------------------------------------ #
# ML-DSA-65                                                            #
# ------------------------------------------------------------------ #
total65, *counts65 = generate(
    param_set      = 'ML-DSA-65',
    sg_int_det_id  = 10,
    sg_int_ndet_id = 22,
    sg_ext_det_id  = 3,
    sg_ext_ndet_id = 15,
    sv_int_id      = 10,
    sv_ext_id      = 3,
    kg_id          = 2,
    dat_path       = os.path.join(OUT_DIR, 'kat_data.c'),
    hdr_path       = os.path.join(OUT_DIR, 'kat_vectors.h'),
    label_suffix   = '',
)

# ------------------------------------------------------------------ #
# ML-DSA-44                                                            #
# ------------------------------------------------------------------ #
total44, *counts44 = generate(
    param_set      = 'ML-DSA-44',
    sg_int_det_id  = 8,
    sg_int_ndet_id = 20,
    sg_ext_det_id  = 1,
    sg_ext_ndet_id = 13,
    sv_int_id      = 8,
    sv_ext_id      = 1,
    kg_id          = 1,
    dat_path       = os.path.join(OUT_DIR, 'kat_data44.c'),
    hdr_path       = os.path.join(OUT_DIR, 'kat_vectors44.h'),
    label_suffix   = '44',
)

print(f'Generated test/kat_vectors.h + kat_data.c     (ML-DSA-65, {total65} cases)')
print(f'Generated test/kat_vectors44.h + kat_data44.c (ML-DSA-44, {total44} cases)')
