"""Generate LibFuzzer harness code from Metis analysis findings."""

import hashlib
import logging
from dataclasses import dataclass, field
from pathlib import Path

from jinja2 import Environment, FileSystemLoader, BaseLoader

from gerrit_fuzzer.gerrit_client import GerritChange, FileDiff
from gerrit_fuzzer.metis_analyzer import AnalysisResult, SecurityFinding

logger = logging.getLogger(__name__)


# Embedded Jinja2 templates for harness generation
HARNESS_TEMPLATE = """\
/*
 * LibFuzzer harness auto-generated by gerrit-fuzzer
 *
 * Target: {{ target_file }}
 * Findings: {{ findings | length }} security issue(s) detected
 * Categories: {{ categories | join(', ') }}
 * Generated from Gerrit change: {{ change_id }}
 */

#include <stdint.h>
#include <stddef.h>
#include <stdlib.h>
#include <string.h>

{% for header in headers %}
#include "{{ header }}"
{% endfor %}

{% if custom_includes %}
{{ custom_includes }}
{% endif %}

{% if setup_code %}
/* Setup / initialization */
{{ setup_code }}
{% endif %}

/*
 * LibFuzzer entry point.
 * data: fuzz input buffer
 * size: length of fuzz input
 */
extern "C" int LLVMFuzzerTestOneInput(const uint8_t *data, size_t size) {
    /* Minimum input size guard */
    if (size < {{ min_input_size }}) return 0;
    {% if max_input_size > 0 %}
    if (size > {{ max_input_size }}) return 0;
    {% endif %}

{% for block in fuzz_blocks %}
    /* Finding: {{ block.finding_msg }} */
    {
{{ block.code | indent(8, first=True) }}
    }

{% endfor %}
    return 0;
}
"""

CMAKEFILE_TEMPLATE = """\
cmake_minimum_required(VERSION 3.16)
project(gerrit_fuzz_harnesses C CXX)

set(CMAKE_C_STANDARD 11)
set(CMAKE_CXX_STANDARD 17)

# LibFuzzer flags
set(FUZZ_FLAGS "-fsanitize=fuzzer,address,undefined -fno-omit-frame-pointer -g")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${FUZZ_FLAGS}")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${FUZZ_FLAGS}")

{% if source_dirs %}
# Include directories from the target project
{% for dir in source_dirs %}
include_directories({{ dir }})
{% endfor %}
{% endif %}

{% for harness in harnesses %}
# Harness: {{ harness.name }}
# Targets: {{ harness.target_file }}
add_executable({{ harness.name }}
    {{ harness.source }}
{% for dep in harness.dependencies %}
    {{ dep }}
{% endfor %}
)
target_link_libraries({{ harness.name }} PRIVATE {{ harness.link_libs | join(' ') }})
{% endfor %}
"""

MAKEFILE_TEMPLATE = """\
# Auto-generated Makefile for fuzzing harnesses
# Compiler: clang/clang++ with LibFuzzer support required

CC ?= clang
CXX ?= clang++
FUZZ_FLAGS = -fsanitize=fuzzer,address,undefined -fno-omit-frame-pointer -g
CFLAGS += $(FUZZ_FLAGS)
CXXFLAGS += $(FUZZ_FLAGS)

{% if include_dirs %}
INCLUDES = {{ include_dirs | join(' ') }}
{% endif %}

.PHONY: all clean

all: {{ harness_names | join(' ') }}

{% for harness in harnesses %}
{{ harness.name }}: {{ harness.source }} {{ harness.dependencies | join(' ') }}
\t$(CXX) $(CXXFLAGS) $(INCLUDES) -o $@ $^

{% endfor %}

clean:
\trm -f {{ harness_names | join(' ') }}
\trm -rf corpus_* crash_*
"""


@dataclass
class FuzzBlock:
    """A block of fuzzing code targeting a specific finding."""
    finding_msg: str
    code: str
    finding: SecurityFinding


@dataclass
class HarnessInfo:
    """Metadata about a generated harness."""
    name: str
    source: str
    target_file: str
    dependencies: list[str] = field(default_factory=list)
    link_libs: list[str] = field(default_factory=list)
    findings: list[SecurityFinding] = field(default_factory=list)
    corpus_hints: list[str] = field(default_factory=list)


def _generate_fuzz_block(finding: SecurityFinding, idx: int) -> FuzzBlock:
    """Generate a fuzzing code block for a specific vulnerability type."""
    generators = {
        "buffer-overflow": _gen_buffer_overflow,
        "heap-overflow": _gen_buffer_overflow,
        "stack-overflow": _gen_buffer_overflow,
        "integer-overflow": _gen_integer_overflow,
        "integer-underflow": _gen_integer_overflow,
        "use-after-free": _gen_use_after_free,
        "double-free": _gen_double_free,
        "null-dereference": _gen_null_deref,
        "out-of-bounds": _gen_oob_access,
        "format-string": _gen_format_string,
        "uninitialized-memory": _gen_uninitialized,
        "memory-corruption": _gen_memory_corruption,
    }

    gen = generators.get(finding.category, _gen_generic)
    code = gen(finding, idx)
    return FuzzBlock(finding_msg=finding.message, code=code, finding=finding)


def _gen_buffer_overflow(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.snippet or f.message}
size_t buf_len_{idx} = size > 256 ? 256 : size;
char *buf_{idx} = (char *)malloc(buf_len_{idx});
if (!buf_{idx}) return 0;
memcpy(buf_{idx}, data, buf_len_{idx});
buf_{idx}[buf_len_{idx} - 1] = '\\0';
// Exercise the target code path with fuzzed buffer
// TODO: Call the actual function from {f.file_path}
free(buf_{idx});"""


def _gen_integer_overflow(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.snippet or f.message}
if (size >= sizeof(uint32_t) * 2) {{
    uint32_t a_{idx}, b_{idx};
    memcpy(&a_{idx}, data, sizeof(uint32_t));
    memcpy(&b_{idx}, data + sizeof(uint32_t), sizeof(uint32_t));
    // Exercise integer arithmetic path from {f.file_path}
    // TODO: Call the actual function that performs the computation
    volatile uint64_t result_{idx} = (uint64_t)a_{idx} * b_{idx};
    (void)result_{idx};
}}"""


def _gen_use_after_free(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.snippet or f.message}
size_t alloc_size_{idx} = (size > 1024) ? 1024 : (size > 0 ? size : 1);
void *ptr_{idx} = malloc(alloc_size_{idx});
if (!ptr_{idx}) return 0;
memcpy(ptr_{idx}, data, alloc_size_{idx});
// Exercise the allocation/deallocation path from {f.file_path}
// TODO: Call the actual function sequence
free(ptr_{idx});"""


def _gen_double_free(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.snippet or f.message}
size_t len_{idx} = (size > 512) ? 512 : (size > 0 ? size : 1);
void *p_{idx} = malloc(len_{idx});
if (!p_{idx}) return 0;
memcpy(p_{idx}, data, len_{idx});
// Exercise the code path from {f.file_path}
// TODO: Call function to test proper free behavior
free(p_{idx});"""


def _gen_null_deref(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.snippet or f.message}
size_t alloc_{idx} = (size > 0) ? size : 1;
if (alloc_{idx} > 65536) alloc_{idx} = 65536;
void *mem_{idx} = malloc(alloc_{idx});
if (mem_{idx}) {{
    memcpy(mem_{idx}, data, alloc_{idx});
    // Exercise the null-check path from {f.file_path}
    // TODO: Call the actual function
    free(mem_{idx});
}}"""


def _gen_oob_access(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.snippet or f.message}
if (size >= 2) {{
    uint8_t index_{idx} = data[0];
    size_t arr_size_{idx} = size - 1;
    const uint8_t *arr_{idx} = data + 1;
    // Exercise array access path from {f.file_path}
    if (index_{idx} < arr_size_{idx}) {{
        volatile uint8_t val_{idx} = arr_{idx}[index_{idx}];
        (void)val_{idx};
    }}
}}"""


def _gen_format_string(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.snippet or f.message}
size_t fmt_len_{idx} = (size > 255) ? 255 : size;
char fmt_{idx}[256];
memcpy(fmt_{idx}, data, fmt_len_{idx});
fmt_{idx}[fmt_len_{idx}] = '\\0';
// Exercise format string path from {f.file_path}
// Note: sanitizers will catch format string bugs
char output_{idx}[1024];
snprintf(output_{idx}, sizeof(output_{idx}), "%s", fmt_{idx});"""


def _gen_uninitialized(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.snippet or f.message}
size_t chunk_{idx} = (size > 4096) ? 4096 : (size > 0 ? size : 1);
uint8_t *region_{idx} = (uint8_t *)malloc(chunk_{idx});
if (!region_{idx}) return 0;
// Partially initialize based on fuzz input
size_t init_len_{idx} = chunk_{idx} / 2;
memcpy(region_{idx}, data, init_len_{idx} < size ? init_len_{idx} : size);
// Exercise the code path from {f.file_path}
// TODO: Call function that may read uninitialized memory
free(region_{idx});"""


def _gen_memory_corruption(f: SecurityFinding, idx: int) -> str:
    return _gen_buffer_overflow(f, idx)


def _gen_generic(f: SecurityFinding, idx: int) -> str:
    return f"""\
// Target: {f.message}
// Category: {f.category}
size_t input_len_{idx} = (size > 4096) ? 4096 : size;
uint8_t *input_{idx} = (uint8_t *)malloc(input_len_{idx} + 1);
if (!input_{idx}) return 0;
memcpy(input_{idx}, data, input_len_{idx});
input_{idx}[input_len_{idx}] = 0;
// Exercise the target code path from {f.file_path}
// TODO: Call the relevant function
free(input_{idx});"""


class HarnessGenerator:
    """Generates LibFuzzer harness files from analysis results."""

    def __init__(self, output_dir: Path, template_dir: Path | None = None):
        self.output_dir = output_dir
        self.output_dir.mkdir(parents=True, exist_ok=True)

        if template_dir and template_dir.exists():
            self.jinja_env = Environment(
                loader=FileSystemLoader(str(template_dir)),
                keep_trailing_newline=True,
            )
        else:
            self.jinja_env = Environment(
                loader=BaseLoader(),
                keep_trailing_newline=True,
            )

    def generate(self, change: GerritChange,
                 analysis: AnalysisResult) -> list[HarnessInfo]:
        """Generate harness files from analysis findings."""
        harnesses = []

        # Group findings by target file
        file_findings = analysis.source_file_findings
        if not file_findings:
            # If no fuzzable findings, create a generic harness for each
            # source file that was modified
            for fd in change.file_diffs:
                if fd.is_source_file and fd.status != "DELETED":
                    info = self._generate_generic_harness(fd, change)
                    if info:
                        harnesses.append(info)
        else:
            for filepath, findings in file_findings.items():
                info = self._generate_targeted_harness(
                    filepath, findings, change
                )
                harnesses.append(info)

        # Generate build files
        self._generate_cmake(harnesses)
        self._generate_makefile(harnesses)

        return harnesses

    def _generate_targeted_harness(
        self, filepath: str, findings: list[SecurityFinding],
        change: GerritChange,
    ) -> HarnessInfo:
        """Generate a harness targeting specific findings in a file."""
        safe_name = self._make_harness_name(filepath)
        source_file = f"{safe_name}.cpp"
        categories = sorted({f.category for f in findings})

        fuzz_blocks = []
        for idx, finding in enumerate(findings):
            block = _generate_fuzz_block(finding, idx)
            fuzz_blocks.append(block)

        headers = [filepath] if Path(filepath).suffix in {".h", ".hpp", ".hxx"} else []

        template = self.jinja_env.from_string(HARNESS_TEMPLATE)
        code = template.render(
            target_file=filepath,
            findings=findings,
            categories=categories,
            change_id=change.change_id,
            headers=headers,
            custom_includes="",
            setup_code="",
            min_input_size=1,
            max_input_size=65536,
            fuzz_blocks=fuzz_blocks,
        )

        harness_path = self.output_dir / source_file
        harness_path.write_text(code, encoding="utf-8")
        logger.info("Generated harness: %s (%d findings)", source_file, len(findings))

        return HarnessInfo(
            name=safe_name,
            source=source_file,
            target_file=filepath,
            findings=findings,
            corpus_hints=[f.snippet for f in findings if f.snippet],
        )

    def _generate_generic_harness(
        self, fd: FileDiff, change: GerritChange,
    ) -> HarnessInfo | None:
        """Generate a generic fuzzing harness for a modified source file."""
        safe_name = self._make_harness_name(fd.new_path)
        source_file = f"{safe_name}.cpp"

        # Extract added function signatures as hints
        added_lines = []
        for hunk in fd.hunks:
            for line in hunk.lines:
                if line.startswith("+"):
                    added_lines.append(line[1:])

        generic_finding = SecurityFinding(
            rule_id="generic-diff-target",
            severity="info",
            message=f"Modified source file: {fd.new_path}",
            file_path=fd.new_path,
            start_line=0,
            end_line=0,
            category="general-security",
            confidence=0.3,
        )

        fuzz_blocks = [FuzzBlock(
            finding_msg=f"Generic fuzzing of modified file {fd.new_path}",
            code=_gen_generic(generic_finding, 0),
            finding=generic_finding,
        )]

        headers = [fd.new_path] if Path(fd.new_path).suffix in {".h", ".hpp", ".hxx"} else []

        template = self.jinja_env.from_string(HARNESS_TEMPLATE)
        code = template.render(
            target_file=fd.new_path,
            findings=[generic_finding],
            categories=["general-security"],
            change_id=change.change_id,
            headers=headers,
            custom_includes="",
            setup_code="",
            min_input_size=1,
            max_input_size=65536,
            fuzz_blocks=fuzz_blocks,
        )

        harness_path = self.output_dir / source_file
        harness_path.write_text(code, encoding="utf-8")
        logger.info("Generated generic harness: %s", source_file)

        return HarnessInfo(
            name=safe_name,
            source=source_file,
            target_file=fd.new_path,
        )

    def _generate_cmake(self, harnesses: list[HarnessInfo]) -> None:
        template = self.jinja_env.from_string(CMAKEFILE_TEMPLATE)
        code = template.render(
            harnesses=harnesses,
            source_dirs=[],
        )
        cmake_path = self.output_dir / "CMakeLists.txt"
        cmake_path.write_text(code, encoding="utf-8")

    def _generate_makefile(self, harnesses: list[HarnessInfo]) -> None:
        template = self.jinja_env.from_string(MAKEFILE_TEMPLATE)
        code = template.render(
            harnesses=harnesses,
            harness_names=[h.name for h in harnesses],
            include_dirs=[],
        )
        makefile_path = self.output_dir / "Makefile"
        makefile_path.write_text(code, encoding="utf-8")

    @staticmethod
    def _make_harness_name(filepath: str) -> str:
        stem = Path(filepath).stem
        safe = "".join(c if c.isalnum() or c == "_" else "_" for c in stem)
        short_hash = hashlib.md5(filepath.encode()).hexdigest()[:6]
        return f"fuzz_{safe}_{short_hash}"
